const nameList = {
  map: "Bản đồ",
  modifyUserInfo: "Chỉnh sửa người dùng",
  riceBuyingAreas: "Danh sách khu vực thu mua",
  riceFields: "Danh sách ruộng lúa",
  riceSeasons: "Danh sách vụ mùa",
  hourlyWeatherForecast: "Dự báo thời tiết theo giờ",
  dailyWeatherForecast: "Dự báo thời tiết theo ngày",
  signUp: "Đăng ký",
  addUserInfo: "Đăng ký thông tin",
  firstScreen: "Đăng nhập",
  ricePrice: "Giá lúa",
  mainScreen: "Màn hình chính",
  calculator: "Máy tính",
  modifyRiceBuyingArea: "Sửa khu vực thu mua",
  modifyRiceField: "Sửa ruộng lúa",
  modifyRiceSeason: "Sửa vụ mùa",
  addRiceBuyingArea: "Thêm khu vực thu mua",
  addRiceField: "Thêm ruộng lúa",
  addRiceSeason: "Thêm vụ mùa",
  riceBuyingAreaInfo: "Thông tin khu vực thu mua",
  userInfo: "Thông tin người dùng",
  riceFieldInfo: "Thông tin ruộng lúa",
  riceSeasonInfo: "Thông tin vụ mùa",
  currentWeather: "Thời tiết hiện tại",
  userOptionModal: "Tùy chọn người dùng",
  test: "Test",
};

export default nameList;
