const nameList = {
  firstScreen: " ", // 1 space
  mainScreen: "  ", // 2 spaces
  userOptionModal: "   ", // 3 spaces
  fullMap: "Bản đồ ruộng lúa",
  modifyUserInfo: "Chỉnh sửa người dùng",
  riceBuyingAreas: "Danh sách khu vực thu mua",
  bills: "Danh sách phiếu thu mua",
  riceFields: "Danh sách ruộng lúa",
  riceSeasons: "Danh sách vụ mùa",
  hourlyWeatherForecast: "Dự báo thời tiết theo giờ",
  dailyWeatherForecast: "Dự báo thời tiết theo ngày",
  addUserInfo: "Đăng ký tài khoản",
  suggestToBuy: "Đề xuất thu mua",
  ricePrice: "Giá lúa",
  contacts: "Liên hệ",
  calculator: "Máy tính",
  billInfo: "Phiếu thu mua",
  suggestToBuys: "Quản lý đề xuất thu mua",
  modifySuggestToBuy: "Sửa đề xuất thu mua",
  modifyRiceBuyingArea: "Sửa khu vực thu mua",
  modifyRiceField: "Sửa ruộng lúa",
  modifyRiceSeason: "Sửa vụ mùa",
  addRiceBuyingArea: "Thêm khu vực thu mua",
  addRiceField: "Thêm ruộng lúa",
  addRiceSeason: "Thêm vụ mùa",
  notifications: "Thông báo",
  suggestToBuyInfo: "Thông tin đề xuất thu mua",
  riceBuyingAreaInfo: "Thông tin khu vực thu mua",
  userInfo: "Thông tin người dùng",
  farmerInfo: "Thông tin nông dân",
  riceFieldInfo: "Thông tin ruộng lúa",
  suggestToBuyInfoForFarmer: "Thông tin về đề xuất thu mua",
  riceSeasonInfoForTrader: "Thông tin về vụ mùa",
  riceSeasonInfo: "Thông tin vụ mùa",
  currentWeather: "Thời tiết hiện tại",
  findFarmers: "Tìm kiếm nông dân",
};

export default nameList;
