const nameList = {
  map: "Bản đồ",
  modifyUserInfo: "Chỉnh sửa người dùng",
  riceBuyingAreas: "Danh sách khu vực thu mua",
  riceFields: "Danh sách ruộng lúa",
  riceSeasons: "Danh sách vụ mùa",
  hourlyWeatherForecast: "Dự báo thời tiết theo giờ",
  dailyWeatherForecast: "Dự báo thời tiết theo ngày",
  signUp: "Đăng ký",
  addUserInfo: "Đăng ký thông tin",
  suggestToBuy: "Đề xuất thu mua",
  firstScreen: "Đăng nhập",
  ricePrice: "Giá lúa",
  mainScreen: "Màn hình chính",
  calculator: "Máy tính",
  suggestToBuys: "Quản lý đề xuất thu mua",
  modifySuggestToBuy: "Sửa đề xuất thu mua",
  modifyRiceBuyingArea: "Sửa khu vực thu mua",
  modifyRiceField: "Sửa ruộng lúa",
  modifyRiceSeason: "Sửa vụ mùa",
  addRiceBuyingArea: "Thêm khu vực thu mua",
  addRiceField: "Thêm ruộng lúa",
  addRiceSeason: "Thêm vụ mùa",
  suggestToBuyInfo: "Thông tin đề xuất thu mua",
  suggestToBuyInfoForFarmer: "Thông tin về đề xuất thu mua",
  riceBuyingAreaInfo: "Thông tin khu vực thu mua",
  userInfo: "Thông tin người dùng",
  farmerInfo: "Thông tin nông dân",
  riceFieldInfo: "Thông tin ruộng lúa",
  riceSeasonInfoForTrader: "Thông tin về vụ mùa",
  riceSeasonInfo: "Thông tin vụ mùa",
  currentWeather: "Thời tiết hiện tại",
  findFarmers: "Tìm kiếm nông dân",
  userOptionModal: "Tùy chọn người dùng",
  test: "Test",
};

export default nameList;
